// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package hello

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	SayHello2(ctx context.Context, opts ...grpc.CallOption) (Greeter_SayHello2Client, error)
	SayHello3(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayHello3Client, error)
	SayHello4(ctx context.Context, opts ...grpc.CallOption) (Greeter_SayHello4Client, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/hello.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayHello2(ctx context.Context, opts ...grpc.CallOption) (Greeter_SayHello2Client, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[0], "/hello.Greeter/SayHello2", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayHello2Client{stream}
	return x, nil
}

type Greeter_SayHello2Client interface {
	Send(*HelloRequest) error
	CloseAndRecv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSayHello2Client struct {
	grpc.ClientStream
}

func (x *greeterSayHello2Client) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterSayHello2Client) CloseAndRecv() (*HelloReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) SayHello3(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayHello3Client, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[1], "/hello.Greeter/SayHello3", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayHello3Client{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_SayHello3Client interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSayHello3Client struct {
	grpc.ClientStream
}

func (x *greeterSayHello3Client) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) SayHello4(ctx context.Context, opts ...grpc.CallOption) (Greeter_SayHello4Client, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[2], "/hello.Greeter/SayHello4", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayHello4Client{stream}
	return x, nil
}

type Greeter_SayHello4Client interface {
	Send(*HelloRequest) error
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSayHello4Client struct {
	grpc.ClientStream
}

func (x *greeterSayHello4Client) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterSayHello4Client) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	SayHello2(Greeter_SayHello2Server) error
	SayHello3(*HelloRequest, Greeter_SayHello3Server) error
	SayHello4(Greeter_SayHello4Server) error
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeterServer) SayHello2(Greeter_SayHello2Server) error {
	return status.Errorf(codes.Unimplemented, "method SayHello2 not implemented")
}
func (UnimplementedGreeterServer) SayHello3(*HelloRequest, Greeter_SayHello3Server) error {
	return status.Errorf(codes.Unimplemented, "method SayHello3 not implemented")
}
func (UnimplementedGreeterServer) SayHello4(Greeter_SayHello4Server) error {
	return status.Errorf(codes.Unimplemented, "method SayHello4 not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayHello2_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).SayHello2(&greeterSayHello2Server{stream})
}

type Greeter_SayHello2Server interface {
	SendAndClose(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterSayHello2Server struct {
	grpc.ServerStream
}

func (x *greeterSayHello2Server) SendAndClose(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterSayHello2Server) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Greeter_SayHello3_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).SayHello3(m, &greeterSayHello3Server{stream})
}

type Greeter_SayHello3Server interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterSayHello3Server struct {
	grpc.ServerStream
}

func (x *greeterSayHello3Server) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_SayHello4_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).SayHello4(&greeterSayHello4Server{stream})
}

type Greeter_SayHello4Server interface {
	Send(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterSayHello4Server struct {
	grpc.ServerStream
}

func (x *greeterSayHello4Server) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterSayHello4Server) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHello2",
			Handler:       _Greeter_SayHello2_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SayHello3",
			Handler:       _Greeter_SayHello3_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SayHello4",
			Handler:       _Greeter_SayHello4_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hello_grpc.proto",
}
